[metadata]
author = "Black Atom Industries"
name = "Black Atom — STA ∷ Research"

[colors]
foreground = "#2b3b33"
background = "#f8f9f9"
cursor_bg = "#66bd10"
cursor_border = "#66bd10"
cursor_fg = "#f8f9f9"
selection_bg = "#e3e8e6"
selection_fg = "#2b3b33"
split = "#66bd10"
compose_cursor = "#f472a0"
scrollbar_thumb = "#75a490"

ansi = [
  "#384b42", # black
  "#e06c8c", # dark_red
  "#4a9a4a", # dark_green
  "#f2a100", # dark_yellow
  "#5b8972", # dark_blue
  "#887bd3", # dark_magenta
  "#3fa569", # dark_cyan
  "#95b8ac" # light_gray
]

brights = [
  "#5b8972", # gray
  "#f472a0", # red
  "#53aa53", # green
  "#66bd10", # yellow
  "#51796d", # blue
  "#998ed9", # magenta
  "#40bf75", # cyan
  "#f8f9f9" # white
]

[colors.tab_bar]
inactive_tab_edge = "#edf1ef"
background = "#f8f9f9"

[colors.tab_bar.active_tab]
fg_color = "#f8f9f9"
bg_color = "#66bd10"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#f8f9f9"
bg_color = "#95b8ac"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#f8f9f9"
bg_color = "#e3e8e6"

[colors.tab_bar.new_tab]
fg_color = "#f8f9f9"
bg_color = "#53aa53"

[colors.tab_bar.new_tab_hover]
fg_color = "#f8f9f9"
bg_color = "#e3e8e6"
intensity = "Bold"
