[metadata]
author = "Black Atom Industries"
name = "Black Atom — CRB ∷ NULL"

[colors]
foreground = "#becedb"
background = "#25333f"
cursor_bg = "#ff964c"
cursor_border = "#ff964c"
cursor_fg = "#25333f"
selection_bg = "#3c4d5c"
selection_fg = "#becedb"
split = "#ff964c"
compose_cursor = "#f7866f"
scrollbar_thumb = "#92a9bb"

ansi = [
  "#25333f", # black
  "#eb6247", # dark_red
  "#92a9bb", # dark_green
  "#ff7c4f", # dark_yellow
  "#92a9bb", # dark_blue
  "#617283", # dark_magenta
  "#617283", # dark_cyan
  "#92a9bb" # light_gray
]

brights = [
  "#617283", # gray
  "#f7866f", # red
  "#b3c1cd", # green
  "#ff964c", # yellow
  "#b3c1cd", # blue
  "#7a8c9d", # magenta
  "#7a8c9d", # cyan
  "#becedb" # white
]

[colors.tab_bar]
inactive_tab_edge = "#1f2a33"
background = "#1f2a33"

[colors.tab_bar.active_tab]
fg_color = "#25333f"
bg_color = "#ff964c"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#25333f"
bg_color = "#3c4d5c"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#25333f"
bg_color = "#2c3d4d"

[colors.tab_bar.new_tab]
fg_color = "#25333f"
bg_color = "#b3c1cd"

[colors.tab_bar.new_tab_hover]
fg_color = "#25333f"
bg_color = "#2c3d4d"
intensity = "Bold"