[metadata]
author = "Black Atom Industries"
name = "Black Atom — CRB ∷ SUPR"

[colors]
foreground = "#344859"
background = "#f2f4f9"
cursor_bg = "#ff8129"
cursor_border = "#ff8129"
cursor_fg = "#f2f4f9"
selection_bg = "#dee6ed"
selection_fg = "#344859"
split = "#ff8129"
compose_cursor = "#ff5533"
scrollbar_thumb = "#566e84"

ansi = [
  "#344859", # black
  "#e63c19", # dark_red
  "#a2b5c5", # dark_green
  "#ff7140", # dark_yellow
  "#a2b5c5", # dark_blue
  "#6c7f92", # dark_magenta
  "#415a70", # dark_cyan
  "#a2b5c5" # light_gray
]

brights = [
  "#6c7f92", # gray
  "#ff5533", # red
  "#bfcbd5", # green
  "#ff8129", # yellow
  "#bfcbd5", # blue
  "#8999a8", # magenta
  "#344859", # cyan
  "#dee6ed" # white
]

[colors.tab_bar]
inactive_tab_edge = "#e8eff2"
background = "#e8eff2"

[colors.tab_bar.active_tab]
fg_color = "#e8eff2"
bg_color = "#ff8129"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e8eff2"
bg_color = "#8999a8"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e8eff2"
bg_color = "#dee6ed"

[colors.tab_bar.new_tab]
fg_color = "#e8eff2"
bg_color = "#bfcbd5"

[colors.tab_bar.new_tab_hover]
fg_color = "#e8eff2"
bg_color = "#dee6ed"
intensity = "Bold"