[metadata]
author = "Black Atom Industries"
name = "Black Atom — MNML ∷ Orange Light"

[colors]
foreground = "#242a2c"
background = "#f2fafd"
cursor_bg = "#fc8e06"
cursor_border = "#fc8e06"
cursor_fg = "#f2fafd"
selection_bg = "#e4edf0"
selection_fg = "#242a2c"
split = "#fc8e06"
compose_cursor = "#fa6d38"
scrollbar_thumb = "#585f61"

ansi = [
  "#474e51", # black
  "#9ea6a9", # dark_red
  "#868e90", # dark_green
  "#0795fd", # dark_yellow
  "#9ea6a9", # dark_blue
  "#868e90", # dark_magenta
  "#9ea6a9", # dark_cyan
  "#9ea6a9" # light_gray
]

brights = [
  "#585f61", # gray
  "#9ea6a9", # red
  "#868e90", # green
  "#fc8e06", # yellow
  "#9ea6a9", # blue
  "#868e90", # magenta
  "#9ea6a9", # cyan
  "#9ea6a9" # white
]

[colors.tab_bar]
inactive_tab_edge = "#ebf3f6"
background = "#f2fafd"

[colors.tab_bar.active_tab]
fg_color = "#ebf3f6"
bg_color = "#fc8e06"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#ebf3f6"
bg_color = "#e4edf0"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#ebf3f6"
bg_color = "#ebf3f6"

[colors.tab_bar.new_tab]
fg_color = "#ebf3f6"
bg_color = "#3aa85b"

[colors.tab_bar.new_tab_hover]
fg_color = "#ebf3f6"
bg_color = "#ebf3f6"
intensity = "Bold"