[metadata]
author = "Black Atom Industries"
name = "Black Atom — NORTH ∷ Dark Night"

[colors]
foreground = "#d8dee9"
background = "#242933"
cursor_bg = "#ebcb8b"
cursor_border = "#ebcb8b"
cursor_fg = "#242933"
selection_bg = "#3b4252"
selection_fg = "#d8dee9"
split = "#ebcb8b"
compose_cursor = "#bf616a"
scrollbar_thumb = "#88c0d0"

ansi = [
  "#242933", # black
  "#bf616a", # dark_red
  "#a3be8c", # dark_green
  "#d08770", # dark_yellow
  "#5e81ac", # dark_blue
  "#b48ead", # dark_magenta
  "#88c0d0", # dark_cyan
  "#88c0d0" # light_gray
]

brights = [
  "#4c566a", # gray
  "#bf616a", # red
  "#a3be8c", # green
  "#ebcb8b", # yellow
  "#81a1c1", # blue
  "#b48ead", # magenta
  "#8fbcbb", # cyan
  "#d8dee9" # white
]

[colors.tab_bar]
inactive_tab_edge = "#1c1f26"
background = "#242933"

[colors.tab_bar.active_tab]
fg_color = "#242933"
bg_color = "#ebcb8b"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#242933"
bg_color = "#434c5e"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#242933"
bg_color = "#2e3440"

[colors.tab_bar.new_tab]
fg_color = "#242933"
bg_color = "#a3be8c"

[colors.tab_bar.new_tab_hover]
fg_color = "#242933"
bg_color = "#2e3440"
intensity = "Bold"