[metadata]
author = "Black Atom Industries"
name = "Black Atom — NORTH ∷ Day"

[colors]
foreground = "#3B4252"
background = "#e9ecf2"
cursor_bg = "#D4B882"
cursor_border = "#D4B882"
cursor_fg = "#e9ecf2"
selection_bg = "#ECEFF4"
selection_fg = "#3B4252"
split = "#D4B882"
compose_cursor = "#B45A63"
scrollbar_thumb = "#5E81AC"

ansi = [
  "#434C5E", # black
  "#A85560", # dark_red
  "#8FA678", # dark_green
  "#B87A66", # dark_yellow
  "#52719A", # dark_blue
  "#9D7E99", # dark_magenta
  "#79ACBD", # dark_cyan
  "#ced6e3" # light_gray
]

brights = [
  "#81A1C1", # gray
  "#B45A63", # red
  "#96AD7F", # green
  "#D4B882", # yellow
  "#7391B0", # blue
  "#A685A1", # magenta
  "#7FA9A8", # cyan
  "#e9ecf2" # white
]

[colors.tab_bar]
inactive_tab_edge = "#dfe4ec"
background = "#e9ecf2"

[colors.tab_bar.active_tab]
fg_color = "#e9ecf2"
bg_color = "#D4B882"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e9ecf2"
bg_color = "#88C0D0"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e9ecf2"
bg_color = "#ced6e3"

[colors.tab_bar.new_tab]
fg_color = "#e9ecf2"
bg_color = "#96AD7F"

[colors.tab_bar.new_tab_hover]
fg_color = "#e9ecf2"
bg_color = "#ced6e3"
intensity = "Bold"