[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Fall Night"

[colors]
foreground = "#e2cdbb"
background = "#1e1815"
cursor_bg = "#eba546"
cursor_border = "#eba546"
cursor_fg = "#1e1815"
selection_bg = "#362a27"
selection_fg = "#e2cdbb"
split = "#eba546"
compose_cursor = "#F48555"
scrollbar_thumb = "#c7ab96"

ansi = [
  "#2a2120", # black
  "#d6815c", # dark_red
  "#9f745e", # dark_green
  "#F48555", # dark_yellow
  "#A47763", # dark_blue
  "#c4997a", # dark_magenta
  "#ef9e74", # dark_cyan
  "#c7ab96" # light_gray
]

brights = [
  "#8a6d58", # gray
  "#F48555", # red
  "#c4926e", # green
  "#eba546", # yellow
  "#d1a68f", # blue
  "#ecc9a2", # magenta
  "#FEBE98", # cyan
  "#e2cdbb" # white
]

[colors.tab_bar]
inactive_tab_edge = "#120e0e"
background = "#1e1815"

[colors.tab_bar.active_tab]
fg_color = "#1e1815"
bg_color = "#eba546"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#1e1815"
bg_color = "#8a6d58"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#1e1815"
bg_color = "#2a2120"

[colors.tab_bar.new_tab]
fg_color = "#1e1815"
bg_color = "#c4926e"

[colors.tab_bar.new_tab_hover]
fg_color = "#1e1815"
bg_color = "#2a2120"
intensity = "Bold"
