[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Fall Day"

[colors]
foreground = "#584538"
background = "#f3eeea"
cursor_bg = "#d48312"
cursor_border = "#d48312"
cursor_fg = "#f3eeea"
selection_bg = "#fdfaf8"
selection_fg = "#584538"
split = "#d48312"
compose_cursor = "#e5764d"
scrollbar_thumb = "#7e6350"

ansi = [
  "#60534c", # black
  "#f2743d", # dark_red
  "#8f6855", # dark_green
  "#c26b22", # dark_yellow
  "#885644", # dark_blue
  "#a0725d", # dark_magenta
  "#e6804c", # dark_cyan
  "#ebded5" # light_gray
]

brights = [
  "#8d6c58", # gray
  "#e5764d", # red
  "#b6764a", # green
  "#d48312", # yellow
  "#a66b5a", # blue
  "#b58464", # magenta
  "#f19258", # cyan
  "#f3eeea" # white
]

[colors.tab_bar]
inactive_tab_edge = "#f0e4dc"
background = "#f3eeea"

[colors.tab_bar.active_tab]
fg_color = "#f3eeea"
bg_color = "#d48312"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#f3eeea"
bg_color = "#a0745d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#f3eeea"
bg_color = "#ebded5"

[colors.tab_bar.new_tab]
fg_color = "#f3eeea"
bg_color = "#b6764a"

[colors.tab_bar.new_tab_hover]
fg_color = "#f3eeea"
bg_color = "#ebded5"
intensity = "Bold"
