[metadata]
author = "Black Atom Industries"
name = "Black Atom — TER ∷ Fall Night"

[colors]
foreground = "#fbd5c2"
background = "#221812"
cursor_bg = "#d68c00"
cursor_border = "#d68c00"
cursor_fg = "#221812"
selection_bg = "#362b25"
selection_fg = "#fbd5c2"
split = "#d68c00"
compose_cursor = "#e87969"
scrollbar_thumb = "#d9b5a2"

ansi = [
  "#2c211b", # black
  "#d96c5d", # dark_red
  "#889776", # dark_green
  "#e67f3c", # dark_yellow
  "#c27e56", # dark_blue
  "#c67a65", # dark_magenta
  "#719b8f", # dark_cyan
  "#d9b5a2" # light_gray
]

brights = [
  "#86563b", # gray
  "#e87969", # red
  "#95a483", # green
  "#d68c00", # yellow
  "#d08c62", # blue
  "#d4896e", # magenta
  "#7ea99c", # cyan
  "#fbd5c2" # white
]

[colors.tab_bar]
inactive_tab_edge = "#190f0a"
background = "#221812"

[colors.tab_bar.active_tab]
fg_color = "#221812"
bg_color = "#d68c00"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#221812"
bg_color = "#86563b"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#221812"
bg_color = "#2c211b"

[colors.tab_bar.new_tab]
fg_color = "#221812"
bg_color = "#95a483"

[colors.tab_bar.new_tab_hover]
fg_color = "#221812"
bg_color = "#2c211b"
intensity = "Bold"
