[metadata]
author = "Black Atom Industries"
name = "Black Atom - JPN - Koyo Hiru"

[colors]
foreground = "#574457"
background = "#f9f2e9"
cursor_bg = "#6aaf9a"
cursor_border = "#6aaf9a"
cursor_fg = "#f9f2e9"
selection_bg = "#908caa"
selection_fg = "#574457"
split = "#529e86"
compose_cursor = "#db7070"
scrollbar_thumb = "#6e6a86"

ansi = [
  "#574457", # black
  "#c65e53", # dark_red
  "#428a68", # dark_green
  "#de8641", # dark_yellow
  "#aa6f83", # dark_blue
  "#ec935f", # dark_magenta
  "#529e86", # dark_cyan
  "#aaa7be", # light_gray
]

brights = [
  "#6e6a86", # gray
  "#db7070", # red
  "#52ad82", # green
  "#ea9d34", # yellow
  "#9175a3", # blue
  "#f0a274", # magenta
  "#6aaf9a", # cyan
  "#eedcc5", # white
]

[colors.tab_bar]
inactive_tab_edge = "#403240"
background = "#eedcc5"

[colors.tab_bar.active_tab]
fg_color = "#f4e8d9"
bg_color = "#ea9d34"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#f4e8d9"
bg_color = "#de8641"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#f4e8d9"
bg_color = "#f0a274"

[colors.tab_bar.new_tab_hover]
fg_color = "#f4e8d9"
bg_color = "#f0a274"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#f4e8d9"
bg_color = "#52ad82"
