[metadata]
author = "Black Atom Industries"
name = "Black Atom — NRD ∷ Day"

[colors]
foreground = "#3B4252"
background = "#ECEFF4"
cursor_bg = "#EBCB8B"
cursor_border = "#EBCB8B"
cursor_fg = "#ECEFF4"
selection_bg = "#ECEFF4"
selection_fg = "#3B4252"
split = "#EBCB8B"
compose_cursor = "#BF616A"
scrollbar_thumb = "#5E81AC"

ansi = [
  "#434C5E", # black
  "#BF616A", # dark_red
  "#A3BE8C", # dark_green
  "#D08770", # dark_yellow
  "#5E81AC", # dark_blue
  "#B48EAD", # dark_magenta
  "#88C0D0", # dark_cyan
  "#D8DEE9" # light_gray
]

brights = [
  "#81A1C1", # gray
  "#BF616A", # red
  "#A3BE8C", # green
  "#EBCB8B", # yellow
  "#81A1C1", # blue
  "#B48EAD", # magenta
  "#8FBCBB", # cyan
  "#ECEFF4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#E5E9F0"
background = "#ECEFF4"

[colors.tab_bar.active_tab]
fg_color = "#ECEFF4"
bg_color = "#EBCB8B"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#ECEFF4"
bg_color = "#88C0D0"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#ECEFF4"
bg_color = "#D8DEE9"

[colors.tab_bar.new_tab]
fg_color = "#ECEFF4"
bg_color = "#A3BE8C"

[colors.tab_bar.new_tab_hover]
fg_color = "#ECEFF4"
bg_color = "#D8DEE9"
intensity = "Bold"