[metadata]
author = "Black Atom Industries"
name = "Black Atom — JPN ∷ Murasaki Yoru"

[colors]
foreground = "#d4bfd6"
background = "#332031"
cursor_bg = "#e6a318"
cursor_border = "#e6a318"
cursor_fg = "#332031"
selection_bg = "#573954"
selection_fg = "#d4bfd6"
split = "#e6a318"
compose_cursor = "#f0635c"
scrollbar_thumb = "#946996"

ansi = [
  "#462c43", # black
  "#ec362d", # dark_red
  "#4cb58a", # dark_green
  "#fe9b15", # dark_yellow
  "#38a6cd", # dark_blue
  "#7e5ba2", # dark_magenta
  "#70a9a8", # dark_cyan
  "#946996" # light_gray
]

brights = [
  "#7d5178", # gray
  "#f0635c", # red
  "#6dc29f", # green
  "#e6a318", # yellow
  "#71c0db", # blue
  "#ec6eaa", # magenta
  "#8fbcbb", # cyan
  "#d4bfd6" # white
]

[colors.tab_bar]
inactive_tab_edge = "#20141f"
background = "#332031"

[colors.tab_bar.active_tab]
fg_color = "#332031"
bg_color = "#e6a318"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#332031"
bg_color = "#6d4769"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#332031"
bg_color = "#462c43"

[colors.tab_bar.new_tab]
fg_color = "#332031"
bg_color = "#6dc29f"

[colors.tab_bar.new_tab_hover]
fg_color = "#332031"
bg_color = "#462c43"
intensity = "Bold"
