[metadata]
author = "Black Atom Industries"
name = "Black Atom — Dark Dimmed"

[colors]
foreground = "#c9dae7"
background = "#1f2625"
cursor_bg = "#afdca9"
cursor_border = "#afdca9"
cursor_fg = "#1f2625"
selection_bg = "#323a39"
selection_fg = "#c9dae7"
split = "#afdca9"
compose_cursor = "#e97292"
scrollbar_thumb = "#73838e"

ansi = [
  "#323a39", # black
  "#91a1ad", # dark_red
  "#91a1ad", # dark_green
  "#73838e", # dark_yellow
  "#5c6b76", # dark_blue
  "#8fbc8a", # dark_magenta
  "#afdca9", # dark_cyan
  "#b6c7d3" # light_gray
]

brights = [
  "#5c6b76", # gray
  "#91a1ad", # red
  "#91a1ad", # green
  "#73838e", # yellow
  "#5c6b76", # blue
  "#8fbc8a", # magenta
  "#afdca9", # cyan
  "#c9dae7" # white
]

[colors.tab_bar]
inactive_tab_edge = "#151c1c"
background = "#1f2625"

[colors.tab_bar.active_tab]
fg_color = "#1f2625"
bg_color = "#afdca9"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#1f2625"
bg_color = "#323a39"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#1f2625"
bg_color = "#282f2f"

[colors.tab_bar.new_tab]
fg_color = "#1f2625"
bg_color = "#4cb86a"

[colors.tab_bar.new_tab_hover]
fg_color = "#1f2625"
bg_color = "#282f2f"
intensity = "Bold"