[metadata]
author = "Black Atom Industries"
name = "Black Atom — Light"

[colors]
foreground = "#1d2722"
background = "#e2efe9"
cursor_bg = "#00b290"
cursor_border = "#00b290"
cursor_fg = "#e2efe9"
selection_bg = "#c8d4cf"
selection_fg = "#1d2722"
split = "#00b290"
compose_cursor = "#ff50a7"
scrollbar_thumb = "#55615c"

ansi = [
  "#1d2722", # black
  "#66726d", # dark_red
  "#899590", # dark_green
  "#78837e", # dark_yellow
  "#66726d", # dark_blue
  "#5981e0", # dark_magenta
  "#0fa05c", # dark_cyan
  "#899590" # light_gray
]

brights = [
  "#55615c", # gray
  "#66726d", # red
  "#899590", # green
  "#78837e", # yellow
  "#66726d", # blue
  "#8d85ed", # magenta
  "#00b290", # cyan
  "#c8d4cf" # white
]

[colors.tab_bar]
inactive_tab_edge = "#d5e2dc"
background = "#e2efe9"

[colors.tab_bar.active_tab]
fg_color = "#d5e2dc"
bg_color = "#00b290"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#d5e2dc"
bg_color = "#c8d4cf"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d5e2dc"
bg_color = "#c8d4cf"

[colors.tab_bar.new_tab]
fg_color = "#d5e2dc"
bg_color = "#00a800"

[colors.tab_bar.new_tab_hover]
fg_color = "#d5e2dc"
bg_color = "#c8d4cf"
intensity = "Bold"