[metadata]
author = "Black Atom Industries"
name = "Black Atom — Light Dimmed"

[colors]
foreground = "#313334"
background = "#eef0f2"
cursor_bg = "#50a648"
cursor_border = "#50a648"
cursor_fg = "#eef0f2"
selection_bg = "#dcdee0"
selection_fg = "#313334"
split = "#50a648"
compose_cursor = "#c70050"
scrollbar_thumb = "#5c6b76"

ansi = [
  "#313334", # black
  "#6d7d88", # dark_red
  "#9dadb9", # dark_green
  "#8595a0", # dark_yellow
  "#6d7d88", # dark_blue
  "#2f8728", # dark_magenta
  "#50a648", # dark_cyan
  "#9dadb9" # light_gray
]

brights = [
  "#5c6b76", # gray
  "#6d7d88", # red
  "#9dadb9", # green
  "#8595a0", # yellow
  "#6d7d88", # blue
  "#2f8728", # magenta
  "#50a648", # cyan
  "#dcdee0" # white
]

[colors.tab_bar]
inactive_tab_edge = "#e4e6e8"
background = "#eef0f2"

[colors.tab_bar.active_tab]
fg_color = "#e4e6e8"
bg_color = "#50a648"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e4e6e8"
bg_color = "#dcdee0"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e4e6e8"
bg_color = "#e4e6e8"

[colors.tab_bar.new_tab]
fg_color = "#e4e6e8"
bg_color = "#008400"

[colors.tab_bar.new_tab_hover]
fg_color = "#e4e6e8"
bg_color = "#e4e6e8"
intensity = "Bold"