[metadata]
author = "Black Atom Industries"
name = "Black Atom — Dark"

[colors]
foreground = "#dcf1e9"
background = "#091a14"
cursor_bg = "#25c9a9"
cursor_border = "#25c9a9"
cursor_fg = "#091a14"
selection_bg = "#1c2d27"
selection_fg = "#dcf1e9"
split = "#25c9a9"
compose_cursor = "#e97292"
scrollbar_thumb = "#72857e"

ansi = [
  "#1c2d27", # black
  "#849790", # dark_red
  "#849790", # dark_green
  "#72857e", # dark_yellow
  "#61746c", # dark_blue
  "#709afb", # dark_magenta
  "#00b9a9", # dark_cyan
  "#d2e7df" # light_gray
]

brights = [
  "#61746c", # gray
  "#849790", # red
  "#849790", # green
  "#72857e", # yellow
  "#61746c", # blue
  "#a59eff", # magenta
  "#25c9a9", # cyan
  "#dcf1e9" # white
]

[colors.tab_bar]
inactive_tab_edge = "#03110c"
background = "#091a14"

[colors.tab_bar.active_tab]
fg_color = "#091a14"
bg_color = "#25c9a9"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#091a14"
bg_color = "#1c2d27"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#091a14"
bg_color = "#13231d"

[colors.tab_bar.new_tab]
fg_color = "#091a14"
bg_color = "#4cb86a"

[colors.tab_bar.new_tab_hover]
fg_color = "#091a14"
bg_color = "#13231d"
intensity = "Bold"