[metadata]
author = "Black Atom Industries"
name = "Black Atom — Light Dimmed"

[colors]
foreground = "#1d2722"
background = "#d5e2dc"
cursor_bg = "#00b290"
cursor_border = "#00b290"
cursor_fg = "#d5e2dc"
selection_bg = "#bbc8c2"
selection_fg = "#1d2722"
split = "#00b290"
compose_cursor = "#ff50a7"
scrollbar_thumb = "#55615c"

ansi = [
  "#1d2722", # black
  "#66726d", # dark_red
  "#899590", # dark_green
  "#78837e", # dark_yellow
  "#66726d", # dark_blue
  "#5981e0", # dark_magenta
  "#0fa05c", # dark_cyan
  "#899590" # light_gray
]

brights = [
  "#55615c", # gray
  "#66726d", # red
  "#899590", # green
  "#78837e", # yellow
  "#66726d", # blue
  "#8d85ed", # magenta
  "#00b290", # cyan
  "#bbc8c2" # white
]

[colors.tab_bar]
inactive_tab_edge = "#c8d4cf"
background = "#d5e2dc"

[colors.tab_bar.active_tab]
fg_color = "#c8d4cf"
bg_color = "#00b290"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#c8d4cf"
bg_color = "#bbc8c2"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c8d4cf"
bg_color = "#bbc8c2"

[colors.tab_bar.new_tab]
fg_color = "#c8d4cf"
bg_color = "#00a800"

[colors.tab_bar.new_tab_hover]
fg_color = "#c8d4cf"
bg_color = "#bbc8c2"
intensity = "Bold"