[metadata]
author = "Black Atom Industries"
name = "Black Atom — Light Dimmed"

[colors]
foreground = "#172822"
background = "#d5eae2"
cursor_bg = "#00b290"
cursor_border = "#00b290"
cursor_fg = "#d5eae2"
selection_bg = "#c2d7ce"
selection_fg = "#172822"
split = "#00b290"
compose_cursor = "#ff50a7"
scrollbar_thumb = "#50625b"

ansi = [
  "#172822", # black
  "#61746c", # dark_red
  "#849790", # dark_green
  "#72857e", # dark_yellow
  "#61746c", # dark_blue
  "#5981e0", # dark_magenta
  "#00a292", # dark_cyan
  "#849790" # light_gray
]

brights = [
  "#50625b", # gray
  "#61746c", # red
  "#849790", # green
  "#72857e", # yellow
  "#61746c", # blue
  "#8d85ed", # magenta
  "#00b290", # cyan
  "#c2d7ce" # white
]

[colors.tab_bar]
inactive_tab_edge = "#cbe0d8"
background = "#d5eae2"

[colors.tab_bar.active_tab]
fg_color = "#cbe0d8"
bg_color = "#00b290"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#cbe0d8"
bg_color = "#c2d7ce"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#cbe0d8"
bg_color = "#c2d7ce"

[colors.tab_bar.new_tab]
fg_color = "#cbe0d8"
bg_color = "#00a800"

[colors.tab_bar.new_tab_hover]
fg_color = "#cbe0d8"
bg_color = "#c2d7ce"
intensity = "Bold"